version: '3'
services:
  kurento:
    image: kurento/kurento-media-server:7.0.0
    volumes:
      - ${HOME}/focusing/volume/kurento:/volume/container
    ports:
      - "8888:8888"
      - "8443:8443"

  nginx:
    image: nginx:latest
    volumes:
      - ${HOME}/focusing/volume/nginx:/volume/container
    ports:
      - "80:80"
      - "443:443"
volumes:
  kurento:
  nginx: