version: '3.7'
services:
  kurento:
    image: kurento/kurento-media-server:7.0.0
    volumes:
      - $HOME/focusing/volume/kurento:/data
    network_mode: host
    environment:
      - KMS_MIN_PORT=5000
      - KMS_MAX_PORT=5050
  nginx:
    image: nginx:latest
    command: |
      /bin/bash -c "
      cp -f data/default.conf etc/nginx/conf.d/default.conf 
      service nginx start 
      sleep infinity"
    volumes:
      - $HOME/focusing/volume/nginx:/data
    ports:
      - "80:80"
      - "443:443"